### ISSUE TITLE
[BUG] Crashes upon startup on Wayland

### ISSUE THREAD

**Issue by murlakatamenka** [afishhh/ftlman#2]
Hi, thanks for the app! Found it because I wanted to write something like that myself, seeing that Slipstream being many moons old and written in Java (that doesn't look pretty on Linux!)

---

`ftlman` fails to start on Wayland (tried on current https://github.com/afishhh/ftlman/commit/2abf7665420cc6b18e13049d97b13cc360757597):

```sh
RUST_BACKTRACE=1 RUST_LOG=1 cargo +nightly run
```

[ftlman @ 2abf766 wayland crash.log](https://github.com/user-attachments/files/16817546/ftlman.%40.2abf766.wayland.crash.log)

Launches and works like this:

```sh
env --unset WAYLAND_DISPLAY cargo +nigtly run
```

and also on pure X11 (tried in i3).

---

Setup details: Arch, Hyprland, mesa on AMD RX 5700 XT (e.g. not Nvidia on Wayland)

**Comment by afishhh** [comment]
Thanks for the issue! I'm surprised a few people actually found it without me doing anything to promote it within the FTL community.
It looks like egui does not provide window rectangles through the viewport input on Wayland, probably because on X11 they also contain the window position which afaik is not easily accessible on Wayland. Luckily I think the `screen_rect` context method provides the size I am looking for and so I replaced it with that instead. [`b731d66`](https://github.com/afishhh/ftlman/commit/b731d66e639ef38bba04d5f506d6e8f7a2ad7135) should work now, I tested it on dwl with an integrated amd gpu.
Honestly the whole "draggable split" part of the gui needs to be cleaned up but making it a standalone widget looks like a pain... anyway the crash should be fixed on master now. I'll make a new release soon (possibly after fixing the second open issue).

**Comment by afishhh** [comment]
I'm going to close this now since I believe the original issue has been fixed and I've created a new release with the changes.

**Comment by murlakatamenka** [comment]
Thanks, I'll check it out shortly and report back so that yoi know it's not only "works on my machine" :)

**Comment by murlakatamenka** [comment]
Yes, it works out-of-the-box now (https://github.com/afishhh/ftlman/commit/afc42d135a1b9119fd6486af92f080eac4f85eb0), thank you very much!
